using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PropertyPayPro.Models;

/// <summary>
/// Recurring maintenance definition — "HVAC service every 6 months on
/// Osborne House", "gutter clean every October". When NextDueDate falls
/// inside the LeadDays window, MaintenanceSchedulerService spawns a
/// ServiceTicket populated from this schedule, then rolls NextDueDate
/// forward by RecurrenceMonths and (optionally) emails tenants and admins.
/// </summary>
public class MaintenanceSchedule
{
    public int Id { get; set; }

    public int PropertyId { get; set; }
    public Property? Property { get; set; }

    [Required, StringLength(200)]
    public string Title { get; set; } = string.Empty;

    [StringLength(2000)]
    public string? Description { get; set; }

    public ServiceCategory Category { get; set; } = ServiceCategory.General;

    [StringLength(120)]
    public string? Vendor { get; set; }

    [StringLength(30)]
    public string? VendorPhone { get; set; }

    /// <summary>Repeat cadence in months. 1 = monthly, 6 = twice a year, 12 = annually.</summary>
    [Range(1, 60)]
    public int RecurrenceMonths { get; set; } = 6;

    /// <summary>Date the next ticket should be created for.</summary>
    [DataType(DataType.Date)]
    public DateOnly NextDueDate { get; set; }

    /// <summary>Create the ticket this many days ahead of NextDueDate so
    /// scheduling / vendor booking has lead time. Default 14 days.</summary>
    [Range(0, 180)]
    public int LeadDays { get; set; } = 14;

    /// <summary>Off switch — paused schedules never generate tickets.</summary>
    public bool Active { get; set; } = true;

    /// <summary>Date the last ticket was auto-generated for this schedule.</summary>
    [DataType(DataType.Date)]
    public DateOnly? LastGeneratedOn { get; set; }

    /// <summary>Id of the last ServiceTicket generated by this schedule
    /// (for quick "view last ticket" links on the schedule list).</summary>
    public int? LastServiceTicketId { get; set; }

    /// <summary>Email every tenant on an active lease at this property
    /// when a ticket is generated, so they know service is coming.</summary>
    public bool NotifyTenants { get; set; } = true;

    /// <summary>Email every Admin/Manager user when a ticket is generated,
    /// so the management team gets a heads-up alongside the tenants.</summary>
    public bool NotifyAdmins { get; set; } = true;

    [StringLength(500)]
    public string? Notes { get; set; }

    [NotMapped]
    public int DaysUntilDue => NextDueDate.DayNumber - DateOnly.FromDateTime(DateTime.UtcNow).DayNumber;

    [NotMapped]
    public bool IsDueNow => Active && DaysUntilDue <= LeadDays;
}
